plugins {
    id 'com.ibm.cics.bundle' version '1.0.8'
    id 'war'
}

group 'com.ibm.cics'
version '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

// ============================================================================
// WAR Configuration
// ============================================================================
war {
    archiveFileName = 'standalone-warupload-demo.war'
}

repositories {
    mavenCentral()
}

cicsBundle {
    libertyWarUpload {
        serverUrl = 'https://your-server:port/com.ibm.cics.wlp.appdeploy/uploadApp'
        //userName = cicsUser // Define cicsUser in gradle.properties file
        //password = cicsPass // Define cicsPass in gradle.properties file
        bearerToken = token // Define token in gradle.properties file

        // Inline XML takes precedence if both are supplied
        applicationXml = '<application id="standalone-warupload-demo" location="standalone-warupload-demo.war" type="war"><context-root>/standalone-warupload</context-root></application>'
        //applicationXmlLocation = 'src/main/resources/application.xml'
    }
}

dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    compileOnly 'com.ibm.cics:com.ibm.cics.server:1.800.1-5.6-PH34012'
    compileOnly 'jakarta.annotation:jakarta.annotation-api:2.1.1'
}
